name: Documentation Style Review

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'docs/**/*.mdx'

jobs:
  markdown-style-check:
    name: Check Markdown Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md" > markdownlint.txt || true

      - name: Install Vale
        run: |
          curl -fsSL https://github.com/errata-ai/vale/releases/download/v3.13.0/vale_3.13.0_Linux_64-bit.tar.gz | tar -xz
          sudo mv vale /usr/local/bin/

      - name: Configure Vale
        run: |
          echo '[styles]' > .vale.ini
          echo 'Microsoft = Microsoft' >> .vale.ini
          echo '[*.md]' >> .vale.ini
          echo 'BasedOnStyles = Microsoft' >> .vale.ini

      - name: Clone Microsoft style guide for Vale
        run: |
          git clone https://github.com/errata-ai/Microsoft.git

      - name: Run Vale
        run: vale "**/*.md" > vale.txt || true

      - name: Install Reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Report markdownlint results
        run: cat markdownlint.txt | reviewdog -efm="%f:%l %m" -name="markdownlint" -reporter=github-pr-review -level=warning

      - name: Report Vale results
        run: cat vale.txt | reviewdog -efm="%f:%l:%c %m" -name="vale" -reporter=github-pr-review -level=info

