name: Docs style review (Microsoft guide, inline)

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'docs/en/**'
      - 'docs/ja/**'
      - 'docs/zh/**'
      - '**/*.md'
      - '**/*.mdx'

permissions:
  contents: read
  pull-requests: write

jobs:
  review-docs:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR HEAD safely
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Microsoft-style inline review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPO_FULL: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python .github/workflows/review-docs.py
